apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: pipelines-vote-api
  name: pipelines-vote-api
spec:
  port:
    targetPort: 9000
  to:
    kind: Service
    name: pipelines-vote-api
    weight: 100
  wildcardPolicy: None

